apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: hello-world
  name: hello-world
  selfLink: /api/v1/namespaces/default/services/hello-world
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  selector:
    run: hello-world
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}